// Generated by CoffeeScript 1.3.3
/*!
* Snockets command-line interface.
*
* Joshua F. Rountree <rountrjf@uc.edu>
* MIT License.
*/

var Snockets, app, commands, concatThem, fs, path, print, snockets, watch;

app = require('./index');

print = console.log;

path = require("path");

Snockets = require('snockets');

snockets = new Snockets();

watch = require('nodewatch');

fs = require("fs");

commands = module.exports;

concatThem = function(sourceFile, buildFile) {
  print('compiling ' + sourceFile);
  return snockets.getConcatenation(sourceFile, {
    minify: false
  }, function(err, js) {
    if (err) {
      print(err);
    }
    if (js) {
      return fs.writeFile(buildFile, js, function(err) {
        if (err) {
          return print(err);
        } else {
          return print("compiled " + sourceFile);
        }
      });
    }
  });
};

/*
Prints current version.

@api public
*/


commands.version = function() {
  return print(require("../package.json").version);
};

commands.watch = function(sourceFile, buildFile) {
  return snockets.getCompiledChain(sourceFile, function(err, jsList) {
    var jsFile, _i, _len, _results;
    watch.add(sourceFile).onChange(function(file, prev, curr, action) {
      return concatThem(sourceFile, buildFile);
    });
    concatThem(sourceFile, buildFile);
    _results = [];
    for (_i = 0, _len = jsList.length; _i < _len; _i++) {
      jsFile = jsList[_i];
      _results.push((function(jsFile) {
        return watch.add(jsFile).onChange(function(file, prev, curr, action) {});
      })(jsFile));
    }
    return _results;
  });
};
