// Generated by CoffeeScript 1.3.3
/*!
* Snockets command-line interface.
*
* Joshua F. Rountree <rountrjf@uc.edu>
* MIT License.
*/

var app, path;

path = require("path");

app = module.exports = require("flatiron").app;

app.config.file({
  file: path.join(__dirname, "..", "data", "config.json")
});